# Generated by Django 3.0.2 on 2022-01-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('agricola', 'Agrícola'), ('ganadero', 'Ganadero')], max_length=50)),
                ('archivo', models.FileField(upload_to='')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('agricola', 'Agrícola'), ('ganadero', 'Ganadero')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('agricola', 'Agrícola'), ('ganadero', 'Ganadero')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('calidad', models.CharField(max_length=50)),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_minimo', models.IntegerField(blank=True, null=True)),
                ('precio_maximo', models.IntegerField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_promedio', models.IntegerField(blank=True, null=True)),
                ('numero_cabezas', models.IntegerField(blank=True, null=True)),
                ('fecha_subida', models.DateField()),
                ('mercado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Mercado')),
                ('variedad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Variedad')),
            ],
        ),
        migrations.AddField(
            model_name='mercado',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Region'),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('region', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('horario_envio', models.CharField(choices=[('todo_el_dia', 'Todo el día'), ('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=15)),
                ('segmento', models.CharField(choices=[('pequena_subsistencia', 'Pequeña Subsistencia'), ('pequena_transicion', 'Pequeña Transición'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=50)),
                ('fecha_primera_entrevista', models.DateField()),
                ('comuna', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Comuna')),
                ('productos', models.ManyToManyField(to='app.Producto')),
                ('region_interes', models.ManyToManyField(to='app.Region')),
            ],
        ),
    ]
